### ISSUE TITLE
Wrong username in changes section

### ISSUE THREAD

**Issue by DaMatrix** [jammehcow/jenkins-discord#3]
What the title says. It seems to show the first part of the email (before the @) rather than the username. Admittedly, a quick skim through the hudson API didn't show any other way of getting the username, so that might be the only way to do it.

Example:
![image](https://user-images.githubusercontent.com/11216106/27976717-09bcadb4-6368-11e7-9480-b579975d849c.png)
(username should be BigBastard, not u0828016)

**Comment by jupjohn** [comment]
My apologies. I seemed to have passed the author object which ended up resolving to your username (not the display name). Should be fixed in the latest commit.

You can get the latest build [here](https://ci.jammehcow.co.nz/job/Discord%20Notifier/7/).

EDIT: my apologies yet again. Pushing yet another change.

**Comment by jupjohn** [comment]
I take that all back. It does seem that jenkins support for usernames is shifty. I'll look into that a bit later, keeping this open for now.

Cheers.
